/**
 * Measurement templates for all garment types
 * Based on real tailor workflows for Indian ethnicwear
 */

import {
  GarmentType,
  MeasureType,
  GarmentMeasurementTemplate,
  MeasurementDefinition,
} from './types';

// ============= Universal Body Measurements =============

export const UNIVERSAL_MEASUREMENTS: MeasurementDefinition[] = [
  {
    key: 'bust_round',
    label_gu: 'છાતી (ગોળ)',
    label_en: 'Bust/Chest (Round)',
    measure_type: MeasureType.ROUND,
    is_essential: true,
    how_to_measure_gu: 'છાતીના સૌથી પહોળા ભાગે ટેપ લગાવો',
    how_to_measure_en: 'Measure around the fullest part of the bust',
    typical_range: [28, 50],
  },
  {
    key: 'underbust_round',
    label_gu: 'છાતીની નીચે (ગોળ)',
    label_en: 'Underbust (Round)',
    measure_type: MeasureType.ROUND,
    is_essential: true,
    how_to_measure_gu: 'છાતીની બરાબર નીચે ટેપ લગાવો',
    how_to_measure_en: 'Measure directly under the bust',
    typical_range: [24, 46],
  },
  {
    key: 'waist_round',
    label_gu: 'કમર (ગોળ)',
    label_en: 'Waist (Round)',
    measure_type: MeasureType.ROUND,
    is_essential: true,
    how_to_measure_gu: 'કમરના સૌથી પાતળા ભાગે ટેપ લગાવો',
    how_to_measure_en: 'Measure around the narrowest part of waist',
    typical_range: [22, 48],
  },
  {
    key: 'hip_round',
    label_gu: 'સીટ / નિતંબ (ગોળ)',
    label_en: 'Hip/Seat (Round)',
    measure_type: MeasureType.ROUND,
    is_essential: true,
    how_to_measure_gu: 'નિતંબના સૌથી પહોળા ભાગે ટેપ લગાવો',
    how_to_measure_en: 'Measure around the fullest part of hips',
    typical_range: [30, 54],
  },
  {
    key: 'shoulder_width',
    label_gu: 'ખાચો',
    label_en: 'Shoulder Width',
    measure_type: MeasureType.WIDTH,
    is_essential: true,
    how_to_measure_gu: 'એક ખભાથી બીજા ખભા સુધી',
    how_to_measure_en: 'Measure from one shoulder point to the other',
    typical_range: [12, 18],
  },
  {
    key: 'neck_round',
    label_gu: 'ગળું (ગોળ)',
    label_en: 'Neck (Round)',
    measure_type: MeasureType.ROUND,
    is_essential: true,
    how_to_measure_gu: 'ગળાના આધારે ટેપ લગાવો',
    how_to_measure_en: 'Measure around the base of the neck',
    typical_range: [12, 18],
  },
  {
    key: 'armhole_round',
    label_gu: 'કચ / આર્મહોલ (ગોળ)',
    label_en: 'Armhole (Round)',
    measure_type: MeasureType.ROUND,
    is_essential: true,
    how_to_measure_gu: 'હાથના છિદ્રની આસપાસ માપો',
    how_to_measure_en: 'Measure around the armhole',
    typical_range: [12, 20],
  },
  {
    key: 'bicep_round',
    label_gu: 'બાંયનો ઉપરનો ભાગ (ગોળ)',
    label_en: 'Bicep (Round)',
    measure_type: MeasureType.ROUND,
    is_essential: false,
    how_to_measure_gu: 'બાંયના સૌથી જાડા ભાગે માપો',
    how_to_measure_en: 'Measure around the fullest part of upper arm',
    typical_range: [9, 18],
  },
  {
    key: 'sleeve_length',
    label_gu: 'બાંય લંબાઈ',
    label_en: 'Sleeve Length',
    measure_type: MeasureType.LENGTH,
    is_essential: true,
    how_to_measure_gu: 'ખભાથી કાંડા સુધી',
    how_to_measure_en: 'Measure from shoulder to wrist',
    typical_range: [16, 26],
  },
  {
    key: 'wrist_round',
    label_gu: 'કફ / કળાઈ (ગોળ)',
    label_en: 'Wrist/Cuff (Round)',
    measure_type: MeasureType.ROUND,
    is_essential: false,
    how_to_measure_gu: 'કાંડાની આસપાસ માપો',
    how_to_measure_en: 'Measure around the wrist',
    typical_range: [5, 9],
  },
];

// ============= Blouse/Choli Template =============

export const BLOUSE_CHOLI_TEMPLATE: GarmentMeasurementTemplate = {
  garment_type: GarmentType.BLOUSE_CHOLI,
  name_gu: 'ચોળી / બ્લાઉઝ',
  name_en: 'Choli / Blouse',
  measurements: [
    {
      key: 'bust_round',
      label_gu: 'છાતી (ગોળ)',
      label_en: 'Bust (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'છાતીના સૌથી પહોળા ભાગે ટેપ લગાવો',
      how_to_measure_en: 'Measure around the fullest part of the bust',
      typical_range: [28, 50],
    },
    {
      key: 'underbust_round',
      label_gu: 'છાતીની નીચે (ગોળ)',
      label_en: 'Underbust (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'છાતીની બરાબર નીચે ટેપ લગાવો',
      how_to_measure_en: 'Measure directly under the bust',
      typical_range: [24, 46],
    },
    {
      key: 'waist_round',
      label_gu: 'કમર (ગોળ)',
      label_en: 'Waist (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'કમરના સૌથી પાતળા ભાગે ટેપ લગાવો',
      how_to_measure_en: 'Measure around the narrowest part of waist',
      typical_range: [22, 48],
    },
    {
      key: 'shoulder_width',
      label_gu: 'ખાચો',
      label_en: 'Shoulder Width',
      measure_type: MeasureType.WIDTH,
      is_essential: true,
      how_to_measure_gu: 'એક ખભાથી બીજા ખભા સુધી',
      how_to_measure_en: 'Measure from one shoulder point to the other',
      typical_range: [12, 18],
    },
    {
      key: 'front_length',
      label_gu: 'આગળ લંબાઈ',
      label_en: 'Front Length',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'ખભાથી આગળની કમર સુધી',
      how_to_measure_en: 'Measure from shoulder to front waist',
      typical_range: [12, 20],
    },
    {
      key: 'back_length',
      label_gu: 'પાછળ લંબાઈ',
      label_en: 'Back Length',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'ખભાથી પાછળની કમર સુધી',
      how_to_measure_en: 'Measure from shoulder to back waist',
      typical_range: [12, 20],
    },
    {
      key: 'armhole_round',
      label_gu: 'કચ (ગોળ)',
      label_en: 'Armhole (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'હાથના છિદ્રની આસપાસ માપો',
      how_to_measure_en: 'Measure around the armhole',
      typical_range: [12, 20],
    },
    {
      key: 'sleeve_length',
      label_gu: 'બાંય લંબાઈ',
      label_en: 'Sleeve Length',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'ખભાથી કાંડા સુધી (સ્લીવલેસ માટે 0)',
      how_to_measure_en: 'Measure from shoulder to wrist (0 for sleeveless)',
      typical_range: [0, 26],
    },
    {
      key: 'bicep_round',
      label_gu: 'બાંય (ગોળ)',
      label_en: 'Bicep (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'બાંયના સૌથી જાડા ભાગે માપો',
      how_to_measure_en: 'Measure around the fullest part of upper arm',
      typical_range: [9, 18],
    },
    {
      key: 'sleeve_opening',
      label_gu: 'બાંયનું મોં / કફ',
      label_en: 'Sleeve Opening / Cuff',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'બાંયના મોંની આસપાસ',
      how_to_measure_en: 'Measure around sleeve opening',
      typical_range: [5, 12],
    },
    {
      key: 'neck_round',
      label_gu: 'ગળું (ગોળ)',
      label_en: 'Neck (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'ગળાના આધારે ટેપ લગાવો',
      how_to_measure_en: 'Measure around the base of the neck',
      typical_range: [12, 18],
    },
    {
      key: 'front_neck_depth',
      label_gu: 'આગળ ગળું ઊંડાઈ',
      label_en: 'Front Neck Depth',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'ગળાથી આગળ કેટલું ઊંડું',
      how_to_measure_en: 'Depth of front neckline',
      typical_range: [2, 10],
    },
    {
      key: 'back_neck_depth',
      label_gu: 'પાછળ ગળું ઊંડાઈ',
      label_en: 'Back Neck Depth',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'ગળાથી પાછળ કેટલું ઊંડું',
      how_to_measure_en: 'Depth of back neckline',
      typical_range: [1, 6],
    },
    {
      key: 'bust_point_height',
      label_gu: 'બસ્ટ પોઇન્ટ ઊંચાઈ',
      label_en: 'Bust Point Height',
      measure_type: MeasureType.LENGTH,
      is_essential: false,
      how_to_measure_gu: 'ખભાથી બસ્ટ પોઇન્ટ સુધી',
      how_to_measure_en: 'From shoulder to bust point',
      typical_range: [8, 14],
    },
    {
      key: 'bust_span',
      label_gu: 'બસ્ટ પોઇન્ટ અંતર',
      label_en: 'Bust Point to Bust Point',
      measure_type: MeasureType.WIDTH,
      is_essential: false,
      how_to_measure_gu: 'એક બસ્ટ પોઇન્ટથી બીજા સુધી',
      how_to_measure_en: 'Distance between bust points',
      typical_range: [6, 10],
    },
    {
      key: 'upper_back_width',
      label_gu: 'પીઠ પહોળાઈ',
      label_en: 'Upper Back Width',
      measure_type: MeasureType.WIDTH,
      is_essential: false,
      how_to_measure_gu: 'પીઠની પહોળાઈ (આર્મહોલ વચ્ચે)',
      how_to_measure_en: 'Back width between armholes',
      typical_range: [10, 16],
    },
  ],
};

// ============= Chaniya/Skirt Template =============

export const SKIRT_CHANIYA_TEMPLATE: GarmentMeasurementTemplate = {
  garment_type: GarmentType.SKIRT_CHANIYA,
  name_gu: 'ઘાઘરો / ચણિયા',
  name_en: 'Chaniya / Ghagra / Lehenga',
  measurements: [
    {
      key: 'waist_round',
      label_gu: 'કમર (ગોળ)',
      label_en: 'Waist (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'કમરે જ્યાં સ્કર્ટ બાંધવાની હોય ત્યાં માપો',
      how_to_measure_en: 'Measure where the skirt will tie at waist',
      typical_range: [22, 48],
    },
    {
      key: 'hip_round',
      label_gu: 'નિતંબ (ગોળ)',
      label_en: 'Hip (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'નિતંબના સૌથી પહોળા ભાગે',
      how_to_measure_en: 'Measure at the fullest part of hips',
      typical_range: [30, 54],
    },
    {
      key: 'skirt_length',
      label_gu: 'લંબાઈ (કમરથી)',
      label_en: 'Length (Waist to Hem)',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'કમરથી જમીન સુધી અથવા જોઈતી લંબાઈ',
      how_to_measure_en: 'From waist to floor or desired length',
      typical_range: [30, 46],
    },
    {
      key: 'gher_flare',
      label_gu: 'ઘેર (નીચેનો ગોળ)',
      label_en: 'Gher / Flare (Bottom Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'સ્કર્ટના તળિયાનો ગોળ માપ',
      how_to_measure_en: 'Circumference of skirt bottom',
      typical_range: [80, 200],
    },
    {
      key: 'waistband_height',
      label_gu: 'કમરપટ્ટી ઊંચાઈ',
      label_en: 'Waistband Height',
      measure_type: MeasureType.LENGTH,
      is_essential: false,
      how_to_measure_gu: 'કમરપટ્ટીની ઊંચાઈ',
      how_to_measure_en: 'Height of waistband',
      typical_range: [1, 3],
    },
  ],
};

// ============= Kameez/Kurti Template =============

export const KAMEEZ_KURTI_TEMPLATE: GarmentMeasurementTemplate = {
  garment_type: GarmentType.KAMEEZ_KURTI,
  name_gu: 'કુર્તી / કમીઝ',
  name_en: 'Kameez / Kurti',
  measurements: [
    {
      key: 'bust_round',
      label_gu: 'છાતી (ગોળ)',
      label_en: 'Bust (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'છાતીના સૌથી પહોળા ભાગે',
      how_to_measure_en: 'Around the fullest part of bust',
      typical_range: [28, 50],
    },
    {
      key: 'waist_round',
      label_gu: 'કમર (ગોળ)',
      label_en: 'Waist (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'કમરની આસપાસ',
      how_to_measure_en: 'Around the waist',
      typical_range: [22, 48],
    },
    {
      key: 'hip_round',
      label_gu: 'નિતંબ (ગોળ)',
      label_en: 'Hip (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'નિતંબની આસપાસ',
      how_to_measure_en: 'Around the hips',
      typical_range: [30, 54],
    },
    {
      key: 'shoulder_width',
      label_gu: 'ખાચો',
      label_en: 'Shoulder Width',
      measure_type: MeasureType.WIDTH,
      is_essential: true,
      how_to_measure_gu: 'એક ખભાથી બીજા ખભા સુધી',
      how_to_measure_en: 'From one shoulder to the other',
      typical_range: [12, 18],
    },
    {
      key: 'kurti_length',
      label_gu: 'કુર્તી લંબાઈ',
      label_en: 'Kurti Length',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'ખભાથી નીચે જોઈતી લંબાઈ',
      how_to_measure_en: 'From shoulder to desired hem',
      typical_range: [24, 48],
    },
    {
      key: 'armhole_round',
      label_gu: 'કચ (ગોળ)',
      label_en: 'Armhole (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'હાથના છિદ્રની આસપાસ',
      how_to_measure_en: 'Around the armhole',
      typical_range: [12, 20],
    },
    {
      key: 'sleeve_length',
      label_gu: 'બાંય લંબાઈ',
      label_en: 'Sleeve Length',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'ખભાથી કાંડા સુધી',
      how_to_measure_en: 'From shoulder to wrist',
      typical_range: [0, 26],
    },
    {
      key: 'bicep_round',
      label_gu: 'બાંય (ગોળ)',
      label_en: 'Bicep (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'બાંયના જાડા ભાગે',
      how_to_measure_en: 'Around upper arm',
      typical_range: [9, 18],
    },
    {
      key: 'cuff_opening',
      label_gu: 'કફ / બાંયનું મોં',
      label_en: 'Cuff Opening',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'બાંયના મોંની આસપાસ',
      how_to_measure_en: 'Around sleeve opening',
      typical_range: [5, 12],
    },
    {
      key: 'neck_round',
      label_gu: 'ગળું (ગોળ)',
      label_en: 'Neck (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'ગળાની આસપાસ',
      how_to_measure_en: 'Around the neck',
      typical_range: [12, 18],
    },
    {
      key: 'side_slit_length',
      label_gu: 'બાજુનું ચીરું લંબાઈ',
      label_en: 'Side Slit Length',
      measure_type: MeasureType.LENGTH,
      is_essential: false,
      how_to_measure_gu: 'બાજુના ચીરાની લંબાઈ',
      how_to_measure_en: 'Length of side slit',
      typical_range: [0, 12],
    },
    {
      key: 'hem_round',
      label_gu: 'નીચેનો ગોળ',
      label_en: 'Hem Round',
      measure_type: MeasureType.ROUND,
      is_essential: false,
      how_to_measure_gu: 'કુર્તીના તળિયાનો ગોળ',
      how_to_measure_en: 'Circumference at bottom hem',
      typical_range: [36, 80],
    },
  ],
};

// ============= Salwar Template =============

export const SALWAR_TEMPLATE: GarmentMeasurementTemplate = {
  garment_type: GarmentType.SALWAR,
  name_gu: 'સલવાર',
  name_en: 'Salwar',
  measurements: [
    {
      key: 'waist_round',
      label_gu: 'કમર (ગોળ)',
      label_en: 'Waist (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'કમરની આસપાસ',
      how_to_measure_en: 'Around the waist',
      typical_range: [22, 48],
    },
    {
      key: 'hip_round',
      label_gu: 'સીટ / નિતંબ (ગોળ)',
      label_en: 'Hip/Seat (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'નિતંબની આસપાસ',
      how_to_measure_en: 'Around the hips',
      typical_range: [30, 54],
    },
    {
      key: 'salwar_length',
      label_gu: 'સલવાર લંબાઈ',
      label_en: 'Salwar Length',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'કમરથી પગની ઘૂંટી સુધી',
      how_to_measure_en: 'From waist to ankle',
      typical_range: [34, 48],
    },
    {
      key: 'thigh_round',
      label_gu: 'જાંઘ (ગોળ)',
      label_en: 'Thigh (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'જાંઘના સૌથી જાડા ભાગે',
      how_to_measure_en: 'Around the fullest part of thigh',
      typical_range: [16, 32],
    },
    {
      key: 'knee_round',
      label_gu: 'ઘૂંટણ (ગોળ)',
      label_en: 'Knee (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: false,
      how_to_measure_gu: 'ઘૂંટણની આસપાસ',
      how_to_measure_en: 'Around the knee',
      typical_range: [12, 20],
    },
    {
      key: 'calf_round',
      label_gu: 'પીંડળી (ગોળ)',
      label_en: 'Calf (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: false,
      how_to_measure_gu: 'પીંડળીની આસપાસ',
      how_to_measure_en: 'Around the calf',
      typical_range: [10, 18],
    },
    {
      key: 'ankle_opening',
      label_gu: 'મોરી / પગનું મોં',
      label_en: 'Ankle Opening / Mori',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'પગના મોંની આસપાસ',
      how_to_measure_en: 'Around ankle opening',
      typical_range: [8, 14],
    },
    {
      key: 'rise_crotch',
      label_gu: 'કચ ઊંડાઈ',
      label_en: 'Rise / Crotch Depth',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'કમરથી કચ સુધી',
      how_to_measure_en: 'From waist to crotch',
      typical_range: [10, 16],
    },
  ],
};

// ============= Churidar Template =============

export const CHURIDAR_TEMPLATE: GarmentMeasurementTemplate = {
  garment_type: GarmentType.CHURIDAR,
  name_gu: 'ચૂડીદાર',
  name_en: 'Churidar',
  measurements: [
    {
      key: 'waist_round',
      label_gu: 'કમર (ગોળ)',
      label_en: 'Waist (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'કમરની આસપાસ',
      how_to_measure_en: 'Around the waist',
      typical_range: [22, 48],
    },
    {
      key: 'hip_round',
      label_gu: 'નિતંબ (ગોળ)',
      label_en: 'Hip (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'નિતંબની આસપાસ',
      how_to_measure_en: 'Around the hips',
      typical_range: [30, 54],
    },
    {
      key: 'churidar_length',
      label_gu: 'ચૂડીદાર લંબાઈ',
      label_en: 'Churidar Length',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'કમરથી પગની ઘૂંટી સુધી (વધારાની લંબાઈ સાથે)',
      how_to_measure_en: 'From waist to ankle (with extra for bangles effect)',
      typical_range: [36, 50],
    },
    {
      key: 'thigh_round',
      label_gu: 'જાંઘ (ગોળ)',
      label_en: 'Thigh (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'જાંઘની આસપાસ',
      how_to_measure_en: 'Around the thigh',
      typical_range: [16, 32],
    },
    {
      key: 'knee_round',
      label_gu: 'ઘૂંટણ (ગોળ)',
      label_en: 'Knee (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'ઘૂંટણની આસપાસ',
      how_to_measure_en: 'Around the knee',
      typical_range: [12, 20],
    },
    {
      key: 'calf_round',
      label_gu: 'પીંડળી (ગોળ)',
      label_en: 'Calf (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'પીંડળીની આસપાસ',
      how_to_measure_en: 'Around the calf',
      typical_range: [10, 18],
    },
    {
      key: 'ankle_round',
      label_gu: 'પગની ઘૂંટી (ગોળ)',
      label_en: 'Ankle (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'પગની ઘૂંટીની આસપાસ',
      how_to_measure_en: 'Around the ankle',
      typical_range: [7, 12],
    },
    {
      key: 'rise_crotch',
      label_gu: 'કચ ઊંડાઈ',
      label_en: 'Rise / Crotch Depth',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'કમરથી કચ સુધી',
      how_to_measure_en: 'From waist to crotch',
      typical_range: [10, 16],
    },
  ],
};

// ============= Pants Template =============

export const PANTS_TEMPLATE: GarmentMeasurementTemplate = {
  garment_type: GarmentType.PANTS,
  name_gu: 'પેન્ટ / પલાઝો',
  name_en: 'Pants / Palazzo',
  measurements: [
    {
      key: 'waist_round',
      label_gu: 'કમર (ગોળ)',
      label_en: 'Waist (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'કમરની આસપાસ',
      how_to_measure_en: 'Around the waist',
      typical_range: [22, 48],
    },
    {
      key: 'high_hip_round',
      label_gu: 'ઉપર નિતંબ (ગોળ)',
      label_en: 'High Hip (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: false,
      how_to_measure_gu: 'કમર નીચે 3-4 ઇંચે',
      how_to_measure_en: 'Around 3-4 inches below waist',
      typical_range: [28, 52],
    },
    {
      key: 'hip_round',
      label_gu: 'નિતંબ (ગોળ)',
      label_en: 'Hip/Seat (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'નિતંબની આસપાસ',
      how_to_measure_en: 'Around the fullest part of hips',
      typical_range: [30, 54],
    },
    {
      key: 'rise_front',
      label_gu: 'આગળ ઊંડાઈ',
      label_en: 'Front Rise',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'કમરથી કચ સુધી આગળથી',
      how_to_measure_en: 'From front waist to crotch',
      typical_range: [9, 14],
    },
    {
      key: 'rise_back',
      label_gu: 'પાછળ ઊંડાઈ',
      label_en: 'Back Rise',
      measure_type: MeasureType.LENGTH,
      is_essential: false,
      how_to_measure_gu: 'કમરથી કચ સુધી પાછળથી',
      how_to_measure_en: 'From back waist to crotch',
      typical_range: [12, 18],
    },
    {
      key: 'inseam',
      label_gu: 'અંદર લંબાઈ (કચથી પગ)',
      label_en: 'Inseam',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'કચથી પગની ઘૂંટી સુધી',
      how_to_measure_en: 'From crotch to ankle',
      typical_range: [26, 36],
    },
    {
      key: 'outseam',
      label_gu: 'બહાર લંબાઈ (કમરથી પગ)',
      label_en: 'Outseam',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'કમરથી પગની ઘૂંટી સુધી બાજુથી',
      how_to_measure_en: 'From waist to ankle along side',
      typical_range: [36, 48],
    },
    {
      key: 'thigh_round',
      label_gu: 'જાંઘ (ગોળ)',
      label_en: 'Thigh (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'જાંઘની આસપાસ',
      how_to_measure_en: 'Around the thigh',
      typical_range: [16, 32],
    },
    {
      key: 'knee_round',
      label_gu: 'ઘૂંટણ (ગોળ)',
      label_en: 'Knee (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'ઘૂંટણની આસપાસ',
      how_to_measure_en: 'Around the knee',
      typical_range: [12, 20],
    },
    {
      key: 'calf_round',
      label_gu: 'પીંડળી (ગોળ)',
      label_en: 'Calf (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: false,
      how_to_measure_gu: 'પીંડળીની આસપાસ',
      how_to_measure_en: 'Around the calf',
      typical_range: [10, 18],
    },
    {
      key: 'hem_opening',
      label_gu: 'પગનું મોં',
      label_en: 'Hem Opening',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'પગના મોંની આસપાસ',
      how_to_measure_en: 'Around leg opening at ankle',
      typical_range: [8, 20],
    },
  ],
};

// ============= Dress/Gown Template =============

export const DRESS_TEMPLATE: GarmentMeasurementTemplate = {
  garment_type: GarmentType.DRESS,
  name_gu: 'ડ્રેસ / ગાઉન',
  name_en: 'Dress / Gown',
  measurements: [
    {
      key: 'bust_round',
      label_gu: 'છાતી (ગોળ)',
      label_en: 'Bust (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'છાતીની આસપાસ',
      how_to_measure_en: 'Around the bust',
      typical_range: [28, 50],
    },
    {
      key: 'underbust_round',
      label_gu: 'છાતીની નીચે (ગોળ)',
      label_en: 'Underbust (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'છાતીની નીચે',
      how_to_measure_en: 'Under the bust',
      typical_range: [24, 46],
    },
    {
      key: 'waist_round',
      label_gu: 'કમર (ગોળ)',
      label_en: 'Waist (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'કમરની આસપાસ',
      how_to_measure_en: 'Around the waist',
      typical_range: [22, 48],
    },
    {
      key: 'hip_round',
      label_gu: 'નિતંબ (ગોળ)',
      label_en: 'Hip (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'નિતંબની આસપાસ',
      how_to_measure_en: 'Around the hips',
      typical_range: [30, 54],
    },
    {
      key: 'shoulder_width',
      label_gu: 'ખાચો',
      label_en: 'Shoulder Width',
      measure_type: MeasureType.WIDTH,
      is_essential: true,
      how_to_measure_gu: 'એક ખભાથી બીજા ખભા સુધી',
      how_to_measure_en: 'From shoulder to shoulder',
      typical_range: [12, 18],
    },
    {
      key: 'dress_length',
      label_gu: 'ડ્રેસ લંબાઈ',
      label_en: 'Dress Length',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'ખભાથી નીચે જોઈતી લંબાઈ',
      how_to_measure_en: 'From shoulder to desired hem',
      typical_range: [30, 60],
    },
    {
      key: 'armhole_round',
      label_gu: 'કચ (ગોળ)',
      label_en: 'Armhole (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'હાથના છિદ્રની આસપાસ',
      how_to_measure_en: 'Around the armhole',
      typical_range: [12, 20],
    },
    {
      key: 'sleeve_length',
      label_gu: 'બાંય લંબાઈ',
      label_en: 'Sleeve Length',
      measure_type: MeasureType.LENGTH,
      is_essential: false,
      how_to_measure_gu: 'ખભાથી કાંડા સુધી',
      how_to_measure_en: 'From shoulder to wrist',
      typical_range: [0, 26],
    },
    {
      key: 'front_neck_depth',
      label_gu: 'આગળ ગળું ઊંડાઈ',
      label_en: 'Front Neck Depth',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'ગળાથી આગળ કેટલું ઊંડું',
      how_to_measure_en: 'Depth of front neckline',
      typical_range: [2, 12],
    },
    {
      key: 'back_neck_depth',
      label_gu: 'પાછળ ગળું ઊંડાઈ',
      label_en: 'Back Neck Depth',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'ગળાથી પાછળ કેટલું ઊંડું',
      how_to_measure_en: 'Depth of back neckline',
      typical_range: [1, 6],
    },
  ],
};

// ============= Kids Generic Template =============

export const KIDS_GENERIC_TEMPLATE: GarmentMeasurementTemplate = {
  garment_type: GarmentType.KIDS_GENERIC,
  name_gu: 'બાળકોનાં કપડાં',
  name_en: 'Kids Clothes',
  measurements: [
    {
      key: 'chest_round',
      label_gu: 'છાતી (ગોળ)',
      label_en: 'Chest (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'છાતીની આસપાસ',
      how_to_measure_en: 'Around the chest',
      typical_range: [18, 32],
    },
    {
      key: 'chest_flat',
      label_gu: 'છાતી (સપાટ)',
      label_en: 'Chest (Flat)',
      measure_type: MeasureType.FLAT,
      is_essential: false,
      how_to_measure_gu: 'છાતી સપાટ માપ',
      how_to_measure_en: 'Chest flat measurement',
      typical_range: [9, 16],
    },
    {
      key: 'waist_round',
      label_gu: 'કમર (ગોળ)',
      label_en: 'Waist (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'કમરની આસપાસ',
      how_to_measure_en: 'Around the waist',
      typical_range: [16, 28],
    },
    {
      key: 'hip_round',
      label_gu: 'નિતંબ (ગોળ)',
      label_en: 'Hip (Round)',
      measure_type: MeasureType.ROUND,
      is_essential: true,
      how_to_measure_gu: 'નિતંબની આસપાસ',
      how_to_measure_en: 'Around the hips',
      typical_range: [18, 32],
    },
    {
      key: 'shoulder_width',
      label_gu: 'ખાચો',
      label_en: 'Shoulder Width',
      measure_type: MeasureType.WIDTH,
      is_essential: true,
      how_to_measure_gu: 'એક ખભાથી બીજા ખભા સુધી',
      how_to_measure_en: 'From shoulder to shoulder',
      typical_range: [8, 14],
    },
    {
      key: 'garment_length',
      label_gu: 'કપડાની લંબાઈ',
      label_en: 'Garment Length',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'ખભાથી નીચે જોઈતી લંબાઈ',
      how_to_measure_en: 'From shoulder to desired length',
      typical_range: [12, 32],
    },
    {
      key: 'sleeve_length',
      label_gu: 'બાંય લંબાઈ',
      label_en: 'Sleeve Length',
      measure_type: MeasureType.LENGTH,
      is_essential: true,
      how_to_measure_gu: 'ખભાથી કાંડા સુધી',
      how_to_measure_en: 'From shoulder to wrist',
      typical_range: [8, 20],
    },
  ],
};

// ============= Template Registry =============

export const GARMENT_TEMPLATES: Record<GarmentType, GarmentMeasurementTemplate> = {
  [GarmentType.BLOUSE_CHOLI]: BLOUSE_CHOLI_TEMPLATE,
  [GarmentType.SKIRT_CHANIYA]: SKIRT_CHANIYA_TEMPLATE,
  [GarmentType.KAMEEZ_KURTI]: KAMEEZ_KURTI_TEMPLATE,
  [GarmentType.SALWAR]: SALWAR_TEMPLATE,
  [GarmentType.CHURIDAR]: CHURIDAR_TEMPLATE,
  [GarmentType.PANTS]: PANTS_TEMPLATE,
  [GarmentType.DRESS]: DRESS_TEMPLATE,
  [GarmentType.KIDS_GENERIC]: KIDS_GENERIC_TEMPLATE,
};

export function getGarmentTemplate(garmentType: GarmentType): GarmentMeasurementTemplate {
  return GARMENT_TEMPLATES[garmentType];
}

export function getEssentialMeasurements(garmentType: GarmentType): MeasurementDefinition[] {
  const template = getGarmentTemplate(garmentType);
  return template.measurements.filter((m) => m.is_essential);
}

export function getAdvancedMeasurements(garmentType: GarmentType): MeasurementDefinition[] {
  const template = getGarmentTemplate(garmentType);
  return template.measurements.filter((m) => !m.is_essential);
}

export function getAllMeasurementKeys(garmentType: GarmentType): string[] {
  const template = getGarmentTemplate(garmentType);
  return template.measurements.map((m) => m.key);
}
